name: CI-D
on:   
  push:
  
jobs:
  run-test:
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - name: running
        continue-on-error: true
        #run: ${{ secrets.SAMPLE }}
        run:  docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container butomo1989/docker-android-x86-7.1.1
